# Generated by Django 4.0.3 on 2022-04-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cantidad_prd',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
