# Generated by Django 4.0.3 on 2022-04-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_factura_cantidad_prd'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pago_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
