# Generated by Django 4.0.3 on 2022-04-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_factura_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='marca',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
